version: '3'
services:
  backend:
    image: bksys-backend
    container_name: backend
    # ports:
    #   - "6666:6666"
    networks:
      - app-network

  frontend:
    image: bksys-frontend
    container_name: frontend
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
