version: '3.8'

services:
  backend:
    image: argoncs12/bksys-backend
    container_name: backend
    ports:
      - "6666:6666"
    restart: always

  frontend:
    image: argoncs12/bksys-frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

networks:
  default:
    driver: bridge